scripts/project_name.txt
In TF-PSA-Crypto this file contains the string "TF-PSA-Crypto". It will be used by scripts as a
robust method for checking which project the script is being called from.
This is part of the work being done to address [Mbed TLS issue #8524](https://github.com/Mbed-TLS/mbedtls/issues/8524). The modifications to the shell scripts to use this new file will be done on the Mbed TLS side, hence just the text file itself is needed here on TF-PSA-Crypto.
Related [Mbed TLS PR](https://github.com/Mbed-TLS/mbedtls/pull/8609).
=> Introduce project_name.txt file

ChangeLog, ChangeLog.d/00README.md, scripts/psa_crypto.py, tests/all_sh_components.txt
Add support to create an initial changelog entry if no entries found and specify the name of the project from the previous entries.
Resolve #47 
Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")
=> Add change log support

docs/driver-only-builds.md, docs/proposed/psa-conditional-inclusion-c.md
This is the crypto part of https://github.com/Mbed-TLS/mbedtls/pull/9818. The last commit is the only new commit, the rest is a result of rebasing the original PR.
I checked for broken references like this:
```
grep -r -ho '[a-zA-Z\_-]*\.md' docs | sort | uniq > filelist.txt
cat filelist.txt | xargs -I filename find . -name filename
<manually check that every file is found>
```
=> Remove USE_PSA from standalone documentation

tests/scripts/all.sh, tests/scripts/components-build-system.sh
Closes [#9755](https://github.com/Mbed-TLS/mbedtls/issues/9755)
- **tests**  not required.
Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) …
=> Out of source build development

scripts/basic.requirements.txt, scripts/ci.requirements.txt, scripts/driver.requirements.txt, scripts/maintainer.requirements.txt, scripts/min_requirements.py
As a part of solving https://github.com/Mbed-TLS/mbedtls-framework/issues/86 and as requested [here](https://github.com/Mbed-TLS/mbedtls/pull/9863#pullrequestreview-2542726294) this PR copies `min_requirements.py` (the new version implemented in https://github.com/Mbed-TLS/mbedtls/pull/9863) and `*.requirements.txt` files from the Mbed TLS repo to this one.
- **tests**  provided | not required because: 
Help make review …
=> [TF-PSA-Crypto] Move most of min_requirements.py to the framework

core/psa_crypto.c
https://github.com/Mbed-TLS/mbedtls-framework/pull/104 fixes a bug whereby some negative tests were always skipped (because they were generated with incorrect dependencies). These test cases fail because the test code is more strict about error behavior than the library. Make the library detect some errors earlier to reconcile it with the test code.
Once this is merged, the CI on https://github.com/Mbed-TLS/mbedtls-framework/pull/104 should pass.
- **tests**  provided | not required because:
=> PSA interruptible sign/verify: detect invalid curve family in start

tests/scripts/components-basic-checks.sh
Enable check_files.py for TF-PSA-Crypto. Closes #51.
- **tests** provided.
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more …
=> Add check files component

tests/scripts/components-basic-checks.sh
This commit adds basic miscellaneous components to TF-PSA-Crypto. Closes #53.
- **tests**  provided | not required because: 
* See our [Guidelines for …
=> Add basic miscellaneous components to TF-PSA-Crypto

core/psa_crypto.c, drivers/builtin/src/psa_crypto_ecp.c
This completes the forward port of https://github.com/Mbed-TLS/mbedtls/pull/9025. This is mostly happening in the framework, but a follow-up to #144 is also needed here.
The CI is expected to fail here due to needing an updated framework in mbedtls. The CI should pass in the [consuming PR](https://github.com/Mbed-TLS/mbedtls/pull/9909).
=> Switch generate_psa_test.py to automatic dependencies for negative test cases

drivers/builtin/src/ecp.c
Added a comment based on an investigation we did at the functional behaviour of a check.  
- **tests**  not required because:  is a minor non functional change.
=> Add mbedtls ecp check framework

tests/scripts/components-sanitizers.sh
This commit adds multiple sanitizer components to TF-PSA-Crypto similar to those found in Mbed TLS. Closes #130 
- **tests**  provided.
* See our [Guidelines for …
=> Add components-sanitizers.sh

tests/scripts/components-configuration-platform.sh
This commit adds multiple configurations to TF-PSA-Crypto similar to those found in Mbed TLS. Closes #68.
- **tests**  provided.
* See our [Guidelines for …
=> Add components configuration platform to TF-PSA-Crypto

tests/scripts/components-compliance.sh
Resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/136
- **tests**  not required because: no test of the test component
=> [tf-psa-crypto] Add components-compliance.sh

docs/architecture/psa-shared-memory.md, programs/psa/key_ladder_demo.sh, programs/psa/psa_hash_demo.sh
Companion PR of https://github.com/Mbed-TLS/mbedtls-framework/pull/131
- **tests**  not required because:  just adapting to the move of a script in the framework
=> Move program files from MbedTLS to MbedTLS Framework

.github/pull_request_template.md
A bug fix to TF-PSA-Crypto should be backported to Mbed TLS if applicable.
- **tests**  not required because: not code
=> PR template checklist: add lines for backports

ChangeLog.d/9652.txt, core/psa_crypto_core.h, drivers/builtin/include/mbedtls/config_adjust_legacy_crypto.h, include/psa/crypto_extra.h, tests/suites/test_suite_md.function
This is the forward porting of https://github.com/Mbed-TLS/mbedtls/pull/9562.
I'm opening the PR here instead of the main repo because MD was moved in this one.
I (manually [^1]) copied all the commits from https://github.com/Mbed-TLS/mbedtls/pull/9562 a part:
- https://github.com/Mbed-TLS/mbedtls/pull/9562/commits/1a2d07d83ac0cd2abf0d1fad12a7dfab5998dfac because there's no such document in tf-psa-crypto
- https://github.com/Mbed-TLS/mbedtls/pull/9562/commits/cc1b26bd9a31642a1afcae135c758fe636b47fb9 because I thought that since tf-psa-crypto never had a release, I doesn't make much sense to add a ChangeLog
[^1]: because I didn't find a way to make git to help me with this (I tried `cherry-pick`, `format-patch` + `am`, `diff` + `apply`).
=> [tf-psa-crypto] md: allow dispatch to PSA whenever CRYPTO_CLIENT is enabled

tests/configs/user-config-for-test.h, tests/configs/user-config-malloc-0-null.h, tests/scripts/components-configuration.sh
This commit adds various configuration components to TF-PSA-Crypto. These components have been adapted from Mbed TLS to use CMake. Closes #125.
This pull request has a dependency on: [#164](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/164)
- **tests**  provided.
=> Add various configuration components

README.md
Fixes link in README.md that point to PSA Crypto API spec.
=> Fix link to PSA Crypto API

ChangeLog.d/168.txt, drivers/builtin/include/mbedtls/lms.h, drivers/builtin/src/lmots.c, drivers/builtin/src/lmots.h, drivers/builtin/src/lms.c, tests/suites/test_suite_lmots.function, tests/suites/test_suite_lms.function
Remove RNG parameters from LMS resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/168
- **tests**  not required because: no changes to test
=> Remove RNG parameters from LMS

include/psa/crypto_config.h
Document https://github.com/Mbed-TLS/mbedtls/issues/9991
In 1.0/4.0, this is pretty straightforward, because everything uses PSA.
(Technically there are a few public API functions that don't use PSA, such as base64, but there's no point in relaxing the requirements on threading just for those.)
- **tests**  not required because: doc only
=> Document PSA's need for threading

drivers/builtin/include/mbedtls/pk.h, drivers/builtin/src/pk.c, drivers/builtin/src/pk_ecc.c, drivers/builtin/src/pk_internal.h, drivers/builtin/src/pk_wrap.c, drivers/builtin/src/pk_wrap.h, drivers/builtin/src/pkparse.c, tests/suites/test_suite_pk.function, tests/suites/test_suite_pkparse.function, tests/suites/test_suite_pkwrite.function
remove the f_rng and p_rng parameter from x509 and PK.
resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/169
Cross-depends on the associated mbedtls PR for a clean CI.
- **tests** covered by existing tests
=> Remove RNG from x509 and PK

docs/4.0-migration-guide/private-decls.md, docs/4.0-migration-guide/private-decls/00README, drivers/builtin/include/mbedtls/private_access.h, programs/test/benchmark.c
Make legacy functions private by guarding their declaration with a macro.
As an example, do `cipher.h` (functions only, I didn't check if some macros and types should become private).
This is up for design review. There is no update to documentation yet. Some open questions:
* Is this approach ok? It's a quick win for not having legacy functions declared .
* Whether we want to update documentation at the same time we make things private, or later.
* Whether we want to add changelog entries, and whether to do it incrementally or all at once at the end.
Resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/219, ~https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/220~ (scope restricted to 219).
~Prerequisite: https://github.com/Mbed-TLS/mbedtls/pull/9868 to avoid breaking mbedtls.~ (Was …
=> Make legacy declarations private: macro guard

tests/suites/test_suite_psa_crypto_entropy.function
Fixes CI error in https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/213 so that https://github.com/Mbed-TLS/mbedtls/pull/10073 can be updated and merged.
- **tests**  not required because:
=> Remove trailing line to fix code style

tests/scripts/components-sanitizers.sh
Release components name should start with "component_release". Their prefix is used to detect them and not run them in PR testing jobs.
- **tests**  not required because: fixing the name of some components
=> Fix release component names

.github/pull_request_template.md
Update the PR template.
- **tests**  not required because: doc only
=> The LTS branch 2.28 is now EOL

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
This was meant to be a side port of https://github.com/Mbed-TLS/mbedtls/pull/10118 but I noticed we didn't have any issue templates yet, so this PR creates them.
Also, while creating this PR I noticed the PR template still had Mbed TLS 2.28 so I removed it while at it.
- **tests** not required because: doc only
=> Add issue templates (same as Mbed TLS)

core/common.h
GCC supports _Static_assert from version 4.6 as a builtin feature even when you compile with std=99.
Use this _Static_assert for the implementation of MBEDTLS_STATIC_ASSERT if there is no defined static_assert.
his is mostly taken from the picolibc methodology just without using the GNUC_PREREQ macro because to improve prortability.
The mentioned picolibc solution:
[github.com/picolibc/picolibc/blob/db4d0fe5952d5ecd714781e3212d4086d970735a/ newlib/libc/include/sys/cdefs.h
](https://github.com/picolibc/picolibc/blob/db4d0fe5952d5ecd714781e3212d4086d970735a/newlib/libc/include/sys/cdefs.h#L387)
Please write a few sentences describing the overall goals of the pull request's commits.
Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the …
=> core: Update common.h to use GCC _Static_assert

ChangeLog.d/removal-of-rng.txt, docs/4.0-migration-guide/rng-removal.md
Add a migration guide for the rng removal and a generic ChangeLog entry for the rng removal that points to it. 
- **tests**  not required because: No changes
=> Add migration guide and ChangeLog

drivers/builtin/include/mbedtls/error_common.h, tests/suites/main_test.function
Fix an omission in https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/167 which is likely to cause test failures when we change more functions to return PSA error codes.
=> Don't call mbedtls_test_hook_error_add()

ChangeLog.d/privatize-part-of-psa_util.txt, core/psa_crypto.c, drivers/builtin/include/mbedtls/psa_util.h, drivers/builtin/src/pk_internal.h, drivers/builtin/src/psa_crypto_ecp.c, drivers/builtin/src/psa_util.c, drivers/builtin/src/psa_util_internal.h, tests/suites/test_suite_psa_crypto.function
Privatize part of psa_util.h resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/231
- **tests**  not required because: No changes
=> Privatize part of psa_util.h

drivers/builtin/src/cipher_wrap.c, drivers/builtin/src/cipher_wrap.h
Constify cipher_wrap:mbedtls_cipher_base_lookup_table
This structure is initialized during the compilation and there is no reason it changes.
Making it const allows the compiler to put it in .rodata section instead of .data one.
=> Constify cipher_wrap:mbedtls_cipher_base_lookup_table

.pylintrc
Side port of https://github.com/Mbed-TLS/mbedtls/pull/10146
=> Pylint: Complain about a missing comma in multiline lists of strings

ChangeLog.d/oid.txt, drivers/builtin/include/mbedtls/crypto_oid.h, drivers/builtin/include/mbedtls/oid.h, drivers/builtin/src/oid.c, drivers/builtin/src/pkcs5.c, drivers/builtin/src/pkparse.c, drivers/builtin/src/pkwrite.c, drivers/builtin/src/rsa.c, tests/suites/test_suite_md.function, tests/suites/test_suite_oid.function, tests/suites/test_suite_pkparse.function, tests/suites/test_suite_pkwrite.function, tests/suites/test_suite_psa_crypto.function
Prepare for `mbedtls/oid.h` to be in Mbed TLS instead of TF-PSA-Crypto. We want this because crypto OIDs don't need to be public, but some X.509 OIDs should be. This is an early step on the way to https://github.com/Mbed-TLS/mbedtls/issues/10124, which needs to be done before the bulk of the work in mbedtls.
In crypto, the OID module will become fully private, so API breaks are fine here.
This is just a small pull request to enable the mbedtls work. Enforcing the private nature of `mbedtls/oid.h` will be done in a follow-up, once mbedtls no longer needs `mbedtls/oid.h` to exist in TF-PSA-Crypto.
- **tests**  provided (this must not break mbedtls)
=> Prepare crypto for the OID module split

drivers/builtin/include/mbedtls/md5.h, drivers/builtin/include/mbedtls/ripemd160.h, drivers/builtin/include/mbedtls/sha1.h, drivers/builtin/include/mbedtls/sha256.h, drivers/builtin/include/mbedtls/sha3.h, drivers/builtin/include/mbedtls/sha512.h
Privatizes all functions in the following files by guarding them with `MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS`
`md5.h`
`ripemd160.h`
`sha1.h`
`sha256.h`
`sha3.h`
`sha512.h`
Also privatizes the type `mbedtls_sha3_id` in `sha3.h` - All of the context types in these files are found in `mbedtls_psa_hash_operation_t` in the file `tf-psa-crypto/include/psa/crypto_builtin_primitives.h` and so are kept unprivatized/internal.
Otherwise there are no other types/macros in these files.
Resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/224
- **tests**  not required because: no functional change
=> Privatize functions and some types in hash headers

ChangeLog.d/union-initialization.txt, core/psa_crypto.c, drivers/builtin/src/psa_crypto_mac.c
Fix https://github.com/Mbed-TLS/mbedtls/issues/9814. Fix https://github.com/Mbed-TLS/mbedtls/issues/9975. See https://github.com/Mbed-TLS/mbedtls/pull/10168 for more explanations.
- **tests**  provided with GCC 15; more to follow in https://github.com/Mbed-TLS/mbedtls-framework/pull/168 and https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/296
=> Fix insufficient union initialization in contexts

drivers/builtin/src/pk.c, drivers/builtin/src/pk_ecc.c, drivers/builtin/src/pk_internal.h, drivers/builtin/src/pk_wrap.c, drivers/builtin/src/pk_wrap.h, drivers/builtin/src/pkparse.c, drivers/builtin/src/pkwrite.c, drivers/builtin/src/pkwrite.h, drivers/builtin/src/psa_util.c, drivers/builtin/src/psa_util_internal.h, include/mbedtls/pk.h, include/tf-psa-crypto/check_config.h, tests/suites/test_suite_pk.data, tests/suites/test_suite_pk.function, tests/suites/test_suite_pkwrite.function
Resolves #283
- **tests**  not required because: removing dead code
=> [tf-psa-crypto] Remove MBEDTLS_USE_PSA_CRYPTO from PK module

include/mbedtls/pk.h
Resolves #274 
~Depends on https://github.com/Mbed-TLS/mbedtls/pull/10130~ (merged).
- **tests**  not required because: removal
=> Remove mbedtls_pk_rsassa_pss_options

ChangeLog.d/move-crypto-struct-inclusion.txt, include/psa/crypto.h
Move the inclusion of crypto_sizes.h and crypto_struct.h in crypto.h
That way when API are declared, the types they used are defined.
This should resolve the issues related to psa_xyz_init functions returning a structure described in Mbed-TLS/mbedtls#7087.
- **tests**  not required because: the change is validated by the current tests. We can't afford the effort required for non-regression testing right now. Covered by  https://github.com/Mbed-TLS/mbedtls/issues/1767.
=> Move the inclusion of crypto_sizes.h and crypto_struct.h in crypto.h

tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function
Improved testing for https://github.com/Mbed-TLS/mbedtls/issues/9814 and https://github.com/Mbed-TLS/mbedtls/issues/9975:
* In unit tests for PSA crypto API multipart operations, use a not-all-bits-zero initializer, simulating what happens with GCC 15. This validates the fix for https://github.com/Mbed-TLS/mbedtls/issues/9814.
* (framework) In test drivers, check that the context is zero on entry to setup. This validates the fix for https://github.com/Mbed-TLS/mbedtls/issues/9975, and also validates that the frontend is robust against https://github.com/Mbed-TLS/mbedtls/issues/9814.
Needs preceding PR:
=> mbedtls: Check union initialization portably

drivers/builtin/include/mbedtls/config_adjust_legacy_crypto.h
Remove the temporary definition for MBEDTLS_SHA3_C created for merging the removal of this macro.
- **tests**  not required because: has tests
=> Remove temporary SHA3 definition

drivers/everest/include/tf-psa-crypto/private/everest/Hacl_Curve25519.h, drivers/everest/include/tf-psa-crypto/private/everest/everest.h, drivers/everest/include/tf-psa-crypto/private/everest/x25519.h, drivers/everest/library/Hacl_Curve25519_joined.c
Resolves #230.
- **tests** not required because: no code change
=> Privatize content in Everest headers

drivers/builtin/include/mbedtls/des.h
Hide DES error with parentheses so that generate_errors.pl skips it, in order to proceed to removing DES instances from the TF PSA Crypto submodule without breaking error generation.
- **tests**  not required because no logic or test-relevant behavior is changed.
- …
=> Hide DES error with parentheses so that generate_errors.pl skips it

programs/test/tfpsacrypto_dlopen.c
Add PSA API-only dynamic loading in tfpsacrypto_dlopen.c
- **tests**  not required because this is a manual test program
* See our [Guidelines for …
=> Add PSA API-only dynamic loading in tfpsacrypto_dlopen.c

ChangeLog.d/rename-mbedtls_pk_setup_opaque.txt, drivers/builtin/src/pk.c, include/mbedtls/pk.h, tests/suites/test_suite_pk.function, tests/suites/test_suite_pkwrite.function
Rename mbedtls_pk_setup_opaque to mbedtls_pk_wrap_psa contributes https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/350
1. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/358
2. https://github.com/Mbed-TLS/mbedtls/pull/10274
3. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/368
=> Rename mbedtls_pk_setup_opaque to mbedtls_pk_wrap_psa

ChangeLog.d/add-version-macros.txt, core/CMakeLists.txt, core/tf_psa_crypto_version.c, drivers/builtin/src/tf_psa_crypto_version.c, include/psa/crypto_config.h, include/tf-psa-crypto/build_info.h, include/tf-psa-crypto/tf_psa_crypto_version.h, include/tf-psa-crypto/version.h, tests/suites/test_suite_tf_psa_crypto_version.data, tests/suites/test_suite_tf_psa_crypto_version.function
Introduce new version macros for TF-PSA-Crypto, analogous to the ones in Mbed TLS. Introduce new convenience functions as well to access the values of these macros (although they may also be accessed directly).
=> Add TF-PSA-Crypto version macros and functions

drivers/builtin/src/aes.c
Make the `selftest` routine in `aes.c` use the new `mbedtls_aes_get_implementation` function so that we are not duplicating preprocessor logic.
Done on the recommendation of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/199#discussion_r2032608311
- **tests**  not required because: no functional change/tests are being changed
=> Make aes_self_test use the new aes_get_implementation function

ChangeLog.d/remove-deprecated-items.txt, drivers/builtin/src/asn1parse.c, include/mbedtls/asn1.h, tests/suites/test_suite_asn1parse.data, tests/suites/test_suite_asn1parse.function
Remove deprecated items, contributes https://github.com/Mbed-TLS/mbedtls/issues/8138
1. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/372
2. https://github.com/Mbed-TLS/mbedtls/pull/10298
=> Remove deprecated items

drivers/builtin/src/pk.c, include/mbedtls/pk.h, tests/suites/test_suite_pk.function
Remove options parameter from mbedtls_pk_verify_ext resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/349
=> Remove options parameter from mbedtls_pk_verify_ext

core/psa_crypto.c, drivers/builtin/src/crypto_oid.h, drivers/builtin/src/oid.c, drivers/builtin/src/pk.c, drivers/builtin/src/pk_ecc.c, drivers/builtin/src/pk_internal.h, drivers/builtin/src/pk_wrap.h, drivers/builtin/src/pkparse.c, drivers/builtin/src/pkwrite.c, drivers/builtin/src/pkwrite.h, drivers/builtin/src/psa_util.c, tests/suites/test_suite_pk.function, tests/suites/test_suite_pkparse.function
include private pk.h internally resolves https://github.com/Mbed-TLS/mbedtls/issues/10263 depends  https://github.com/Mbed-TLS/mbedtls/pull/10315
1. https://github.com/Mbed-TLS/mbedtls/pull/10272
2. https://github.com/Mbed-TLS/mbedtls/pull/10315
3. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/357
- **tests**  not required because: No changes
=> include private pk.h internally

drivers/builtin/src/pk.c, include/mbedtls/pk.h
Remove duplicate definition to complete the rename of mbedtls_pk_setup_opaque depends https://github.com/Mbed-TLS/mbedtls/pull/10274 resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/350.
1. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/358
2. https://github.com/Mbed-TLS/mbedtls/pull/10274
3. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/368
- **tests**  not required because: No changes.
=> Remove duplicate definition.

drivers/builtin/src/pk.c, include/mbedtls/pk.h, tests/suites/test_suite_pk.function
Remove the alias and replace it with the real enum https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/346 depends https://github.com/Mbed-TLS/mbedtls/pull/10271
1. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/356
2. https://github.com/Mbed-TLS/mbedtls/pull/10271
3. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/377
- **tests**  not required because: No changes
=> Remove alias

core/common.h, drivers/builtin/src/pk_rsa.c
Remove the compatibility `common.h`
Fixes https://github.com/Mbed-TLS/mbedtls/issues/9862
- **tests** not required because: No functional changes
- The merge order of the PRs proceeds from top to bottom:
=> Remove compat common.h

include/psa/crypto_extra.h
This should fix the code-style errors from uncrustify.
- **tests** not required
=> Fix whitespace in crypto_extra.h

doxygen/tfpsacrypto.doxyfile.in
Don't render files in `include/mbedtls/private`
- **tests**  not required because: documentation changes
=> Remove `include/mbedtls/private` from Doxygen

ChangeLog.d/threading.txt, core/psa_crypto.c, core/psa_crypto_slot_management.c, docs/4.0-migration-guide/threading.md, drivers/builtin/src/threading.c, drivers/builtin/src/threading_internal.h, include/mbedtls/threading.h, include/psa/crypto_config.h, tests/suites/test_suite_platform_threading.data, tests/suites/test_suite_platform_threading.function
https://github.com/Mbed-TLS/mbedtls/issues/8455#issuecomment-3234697006
* Separate the API functions from the function pointers for mutex functions.
* Separate the API type from the platform type for mutex objects.
* Hide things from `<mbedtls/threading.h>` that applications should not reference in `threading_internal.h`.
* Document the mutex functions.
* Modernize error codes.
* Implement condition variables, following the model now established for mutexes.
* Smoke tests (single-threaded)
**Depends on:** https://github.com/Mbed-TLS/mbedtls-framework/pull/204
- **tests**  provided (except for `MBEDTLS_THREADING_ALT` which is not tested)
=> Surface cleaning of mutex interface and add condition variables

CMakeLists.txt, core/psa_crypto.c, core/psa_crypto_random_impl.h, core/tf_psa_crypto_check_config.h, core/tf_psa_crypto_common.h, drivers/builtin/include/mbedtls/private/ctr_drbg.h, include/psa/crypto_adjust_config_synonyms.h, include/psa/crypto_config.h, tests/scripts/components-configuration-platform.sh, tests/scripts/test_config_checks.py, tests/suites/test_suite_config.crypto_combinations.data
Cleanup following the simplification of entropy and RNG options
Address partially:
- https://github.com/Mbed-TLS/mbedtls/issues/10300 (removal of MBEDTLS_PLATFORM_GET_ENTROPY_ALT, test to validate that an NV-seed-only configuration requires MBEDTLS_ENTROPY_NO_SOURCES_OK)
- https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/370 (error out at compile time if no entropy source, compile-time checks related to prediction resistance).
Address the two remaining comments from @yanesca in #419:
- https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/419#discussion_r2329549902
- https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/419#discussion_r2329802201
This PR requires both Mbed-TLS/mbedtls-framework#208 and Mbed-TLS/mbedtls#10393 to be merged to pass CI.
It has been validated by …
=> Cleanup following the simplification of entropy and RNG options

ChangeLog.d/psa_can_do_cipher.txt, core/psa_crypto_core.h, include/psa/crypto_extra.h
Fixes https://github.com/Mbed-TLS/mbedtls/issues/10341.
=> Declare psa_can_do_cipher() publicly

include/psa/crypto_config.h
I simply tried to remove/fix some references to old build symbols and paths that I found in `include/psa/crypto_config.h`.
This PR doesn't have an associated issue.
- **tests** not required because: no code change to be tested
=> crypto_config: fix documentation by removing mentions to unexisting build symbols

ChangeLog.d/config-version.txt, include/psa/crypto_config.h, include/tf-psa-crypto/build_info.h
`TF_PSA_CRYTPO_CONFIG_VERSION` replicates the existing (but so far unused) `MBEDTLS_CONFIG_VERSION`.
=> Introduce TF-PSA-Crypto config version

core/.gitignore, core/CMakeLists.txt, scripts/generate_config_checks.py
Introduce `generate_config_checks.py` and instructions to use it in the build scripts. Do not yet consume the generated files, to avoid breaking the build in mbedtls (mbedtls needs to know how to generate the crypto files before crypto can start having them when it's built by mbedtls).
Contributes to https://github.com/Mbed-TLS/mbedtls/issues/10147. See https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/269 for what this will look like when consumed by the library.
Needs preceding PR: https://github.com/Mbed-TLS/mbedtls-framework/pull/196
=> Introduce generated config checks in crypto

ChangeLog.d/pk-simplify-rsa-padding.txt, drivers/builtin/src/pk.c, drivers/builtin/src/pk_rsa.c, drivers/builtin/src/pk_wrap.c, drivers/builtin/src/pk_wrap.h, include/mbedtls/pk.h, include/mbedtls/private/pk_private.h, programs/fuzz/fuzz_privkey.c
Resolve #347 and resolve #205
**Depends on:** https://github.com/Mbed-TLS/mbedtls/pull/10418 for a clean CI (sigh).
- **tests**  not required because: docs only
=> Finalize pk.h

docs/4.0-migration-guide/pk.md
Based on comparing pk.h in 3.6 and
https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/468.
Together with https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/468 and https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/472, resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/209.
I'll remove the stub in `md-pk.md` in a separate PR.
- **tests**  provided | not required because:
=> PK migration guide

core/psa_crypto.c, include/mbedtls/pk.h, include/psa/crypto_values.h
Update the value of `PSA_KEY_USAGE_DERIVE_PUBLIC` based on the [API draft](https://github.com/ARM-software/psa-api/pull/282).
Needs preceding PR:
=> Update value of PSA_KEY_USAGE_DERIVE_PUBLIC

docs/4.0-migration-guide/pake.md
Populate the PAKE section of the 1.0 migration guide. Resolves #335
Based on:
- the PSA ChangeLog (link in the document);
- the "Update PAKE API to 1.2" EPIC on [the board](https://github.com/orgs/Mbed-TLS/projects/18/views/1):
- looking at changes in `crypto_extra.h`,
- using mbedtls PRs as a basis for the before-after examples.
- **tests**  not required because: documentation
=> Migration guide: PAKE
